const HOME_PAGE_CONSTANTS = {
    GET_ALL_POSTS_REQUEST:"GET_ALL_POSTS_REQUEST",
    GET_ALL_POSTS_SUCCESS:"GET_ALL_POSTS_SUCCESS",
    GET_ALL_POSTS_FAILURE:"GET_ALL_POSTS_FAILURE",
    GET_ALL_USERS_REQUEST:"GET_ALL_USERS_REQUEST",  
    GET_ALL_USERS_SUCCESS:"GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_FAILURE:"GET_ALL_USERS_FAILURE",
    CLEAR_ALL_POSTS:"CLEAR_ALL_POSTS"
  };
  
  export default HOME_PAGE_CONSTANTS;