const POST_PAGE_CONSTANTS = {
        GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
        GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
        GET_POSTS_FAILURE: "GET_POSTS_FAILURE",
};
    
    export default POST_PAGE_CONSTANTS